### ISSUE TITLE
Underground Jungle & Vault holy mountain items not shown correctly

### ISSUE THREAD

**Issue by roncli** [ScipioWright/Noita-poptracker#2]
The underground jungle's holy mountain shop items and spell refresh, and the vault's holy mountain shop items do not update when purchased.

The Archipelago tracker does show them as checked.  https://archipelago.gg/tracker/E368JBVURp6z5IhsKJI82A/0/29

**Comment by roncli** [comment]
![image](https://github.com/ScipioWright/Noita-poptracker/assets/498929/69023916-5a84-4277-b701-36d3ea3dedc8) 
![image](https://github.com/ScipioWright/Noita-poptracker/assets/498929/85a475a3-463c-4885-a23d-e43529b1185c)

**Comment by ScipioWright** [comment]
Are other shops updating properly?

**Comment by ScipioWright** [comment]
Are you using the latest release? It looks like this issue was solved in the update on May 2nd, 2023.

**Comment by roncli** [comment]
Yes, other locations are updating correctly, including other holy mountains.

This is the URL I downloaded from: https://github.com/ScipioWright/Noita-poptracker/releases/download/1.1.0/Noita-poptracker.zip

**Comment by ScipioWright** [comment]
It has been almost a year since this release and nobody has ever brought this up until now lmao.
But yeah, the release is using the wrong version of the code.
I'll make a new release now fixing it.
Please confirm that the new release fixes your issue so I can close this after.

**Comment by roncli** [comment]
:D I just started playing Archipelago a week ago (although I've been playing Noita since early access), and just noticed it on a large multiworld run I'm doing with a bunch of other folks.

The underground jungle is fixed, but the vault is not.

**Comment by ScipioWright** [comment]
Whoops, my bad -- forgot a few slashes. I'm at work and can't really test it before pushing it, unfortunately.
I updated the release, it should work now. Please confirm whether it does, thank you!

**Comment by roncli** [comment]
~~Unfortunately still no change, the vault's holy mountain is still showing green despite everything bought.~~

Wait, after reloading, it appears to have worked.  I still show 1 item left now instead of 5... but I think that's not poptracker but rather the NoitaArchipelago mod not loading all the checks (I remember there only being 4 checks there out of the 10 spells)

**Comment by ScipioWright** [comment]
Well, crap, that's also a problem then. Not sure why though... will note to investigate it later.
If you can, put another issue up on the Noita mod github, include the logger.log file in your Noita folder.

**Comment by roncli** [comment]
OK this is weird.  The tracker says I have all 5 checks, but poptracker is showing I have 4.

**Comment by ScipioWright** [comment]
...I missed another slash. I really should have waited until I was home to do all this.
Should be fixed in a minute or so when I upload the release

**Comment by roncli** [comment]
Bingo!  Thanks for the fix. :)
![image](https://github.com/ScipioWright/Noita-poptracker/assets/498929/99c9296d-969e-435c-80a7-e0f159046751)
